[tool.poetry]
name = "NerpyBot"
version = "0.0.0"
description = ""
repository = "https://github.com/nerdycraft/NerpyBot"
authors = [
    "Rico Wesenberg <r.wesenberg@gmail.com>",
    "Dennis Bernardy <bernardyd@gmail.com>"
]
license = "GPL-3.0-or-later"
readme = "README.md"
packages = [
    { include = "NerdyPy" }
]

[tool.poetry.dependencies]
python = "^3.11"
google-api-python-client = "^2.90.0"
SQLAlchemy = "^2.0.17"
pymysql = "^1.0.3"
youtube_dl = { git = "https://github.com/ytdl-org/youtube-dl.git", branch = "master" }
pydub = "^0.25.1"
ffmpeg-python = "^0.2.0"
"discord.py" = {extras = ["voice"], version = "==2.3.2"}
python-blizzardapi = "^1.3.0"
pytimeparse = "^1.1.8"
humanize = "^4.8.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
black = {extras = ["d"], version = "^23.7.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ["py311"]
line-length = "120"