name: Build Docker Image

on:
  push:
    branches:
      - master
      - 'releases/**'

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Container Meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: nerdycraft/nerdybot
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
            {{major}}.{{minor}}.{{patch}}

      - name: Github Container Meta
        id: github_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/nerdybot
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
            {{major}}.{{minor}}.{{patch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            ${{ steps.github_meta.outputs.tags }}
          labels: |
            ${{ steps.docker_meta.outputs.labels }}
            ${{ steps.github_meta.outputs.labels }}
