name: Build Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker Container Meta
        id: docker_meta_nerpybot
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/ethernerd-net/nerpybot
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Docker Container Meta
        id: docker_meta_database-migrations
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/ethernerd-net/nerpybot-database-migrations
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Nerpybot
        id: build_nerdybot
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_nerpybot.outputs.tags }}
          labels: ${{ steps.docker_meta_nerpybot.outputs.labels }}

      - name: Build and push Database Migrations
        id: build_database-migrations
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./database_migrations.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_database-migrations.outputs.tags }}
          labels: ${{ steps.docker_meta_database-migrations.outputs.labels }}
